# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  test:
    runs-on: ubuntu-latest
    environment: production
    env:
      BASE_URL: ${{vars.BASE_URL}}
      LOGIN: ${{secrets.LOGIN}}
      PASSWORD: ${{secrets.PASSWORD}}
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 14.15.4
      uses: actions/setup-node@v3
      with:
        node-version: 14.15.4
        cache: 'npm'
    - run: npm ci
    - run: npm run test
